package com.starttohkar.model;

import java.io.Serializable;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Table
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Book implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -1670893016517855654L;
    @Id
    @GeneratedValue
    @Schema(description = "autogenerated id")
    private int bookId;
    @Schema(description = "this is the book name")
    private String bookName;
    @Schema(description = "this is book price")
    private double price;
}